IF(EXISTS "${CMAKE_SOURCE_DIR}/../qtkeychain/keychain.h")
  SET(QTKEYCHAIN_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/../qtkeychain/)
ELSE()
  FIND_PATH(QTKEYCHAIN_INCLUDE_PATH NAMES qtkeychain/.h qtkeychain.h HINTS $ENV{QTKEYCHAIN_DIR} )
ENDIF()

IF(EXISTS "${CMAKE_SOURCE_DIR}/../buildqtkeychain/")
  IF( WIN32 )
     SET(QTKEYCHAIN_LIBRARY ${CMAKE_SOURCE_DIR}/../win/buildqtkeychain/libqtkeychain.dll)
  ELSE( WIN32 )
     SET(QTKEYCHAIN_LIBRARY ${CMAKE_SOURCE_DIR}/../buildqtkeychain/libqtkeychain.so)
  ENDIF( WIN32 )
ELSE()
  FIND_LIBRARY(QTKEYCHAIN_LIBRARY NAMES qtkeychain HINTS $ENV{QTKEYCHAIN_DIR})
ENDIF()

SET(QTKEYCHAIN_INCLUDE_DIR ${QTKEYCHAIN_INCLUDE_PATH})

# handle the QUIETLY and REQUIRED arguments and set QTKEYCHAIN_FOUND to TRUE if
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QtKeyChain DEFAULT_MSG
  QTKEYCHAIN_LIBRARY QTKEYCHAIN_INCLUDE_PATH)

MARK_AS_ADVANCED( QTKEYCHAIN_INCLUDE_PATH QTKEYCHAIN_LIBRARY )
